version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_HEADERS_X-Content-Type-Options=[nosniff]
    volumes:
      - "./config.yml:/etc/docker/registry/config.yml"
    container_name: registry
  registry-ui:
    image: joxit/docker-registry-ui:static
    restart: always
    ports:
      - "80:80"
    environment:
      - REGISTRY_TITLE=My Internal Docker Registry
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
    container_name: registry-ui
